#!/usr/bin/env bash
# Installing `nginx` listening on port 80.
# When querying Nginx  at its root `/` with a GET request (requesting a page) using `curl`, it must return a page that contains the string `Hello World!`.

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
