#!/usr/bin/env bash
# Configuring Nginx so that its HTTP response contains a custom header :
#	* The name of the custom HTTP header is `X-Served-By`.
#	* The value of the custom HTTP header is the hostname of the server Nginx is running on.

apt-get update
apt-get install -y nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo 'server {
	listen 80 default_server;
        listen [::]:80 default_server;

	add_header X-Served-By $HOSTNAME;

        root /var/www/html;
        index index.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

	error_page 404 /404.html;
	location = /404.html{
		internal;
	}

}' > /etc/nginx/sites-available/default
service nginx restart
