#!/usr/bin/env bash
# Finding out what's keeping my Ubuntu container's Nginx installation
# from listening on port 80, debugging and fixing the issue.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
