#!/usr/bin/env bash
# Displays numbers from 1 to 100, but `FizzBuzz` when the number is a multiple of 3 and 5, `Fizz` when multiple of 3 and `Buzz` when multiple of 5.

for n in {1..100}
do
	if (( n % 3 == 0 && n % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( n % 3 == 0 ))
	then
		echo "Fizz"
	elif (( n % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$n"
	fi
done
