#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays this data in a list format ordered from the greatest to the lowest number of occurrences using `awk`.

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
