#!/usr/bin/env bash
# Displays `Best School` 10 times using `while`, but if 9th iteration displays `Hi` on a new line after it.

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
